import Link from "next/link";

export const metadata = {
  title: "Terms of Service | Smart Kitchen",
  description:
    "Read Smart Kitchen's terms of service, including payment terms, shipping policies, and user responsibilities.",
};

const lastUpdated = "November 7, 2025";

export default function TermsOfServicePage() {
  return (
    <main className="container mx-auto max-w-3xl py-12 md:py-20">
      <h1 className="font-semibold text-3xl md:text-4xl">Terms of Service</h1>
      <p className="mt-3 text-muted-foreground">Last Updated on: {lastUpdated}</p>

      <section className="mt-8 space-y-4">
        <h2 className="font-semibold text-2xl">1. Electronic Record</h2>
        <p className="text-muted-foreground">
          This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as
          applicable and the amended provisions pertaining to electronic records in various statutes as amended by the
          Information Technology Act. This electronic record is generated by a computer system and does not require any
          physical or digital signatures.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-semibold text-2xl">2. Products & Orders</h2>
        <ul className="list-disc space-y-2 pl-6 text-muted-foreground">
          <li>All products listed on our site are subject to availability.</li>
          <li>We reserve the right to discontinue or modify any product without prior notice.</li>
          <li>Prices are displayed in INR and include/exclude taxes (as mentioned on product pages).</li>
          <li>Placing an order indicates acceptance of product details, pricing, and policies.</li>
        </ul>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-semibold text-2xl">3. Payment Terms</h2>
        <p className="text-muted-foreground">
          We accept payments via Credit/Debit Cards, Net Banking, UPI, and Wallets through secure payment gateways.
          Orders will be processed only after successful payment confirmation. Smart Kitchen will not be responsible for
          payment failures due to technical issues at the payment gateway or bank&apos;s end.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-semibold text-2xl">4. Shipping & Delivery</h2>
        <p className="text-muted-foreground">
          Orders are usually dispatched within the estimated timelines mentioned on product pages. Delivery times may
          vary based on your location and courier availability. Smart Kitchen is not liable for delays caused by
          third-party courier partners.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-semibold text-2xl">5. Returns & Refunds</h2>
        <p className="text-muted-foreground">
          We follow a hassle-free return and exchange policy subject to certain conditions. Products must be returned
          unused, in original packaging, and within the specified return window. Refunds, if applicable, will be
          processed back to the original payment method.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-semibold text-2xl">6. User Responsibilities</h2>
        <p className="text-muted-foreground">
          You agree not to misuse our website or services. Providing false information, engaging in fraudulent
          transactions, or violating applicable laws may result in suspension or termination of your account.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-semibold text-2xl">7. Intellectual Property</h2>
        <p className="text-muted-foreground">
          All content, images, logos, and materials on our website are the intellectual property of Smart Kitchen.
          Unauthorized use, reproduction, or distribution is strictly prohibited without prior written consent.
        </p>
      </section>

      <section className="mt-10 space-y-4">
        <h2 className="font-semibold text-2xl">Contact Us</h2>
        <p className="text-muted-foreground">
          For questions about these Terms of Service, contact us at{" "}
          <Link className="underline" href="mailto:info@smartkitchen.store">
            info@smartkitchen.store
          </Link>{" "}
          or by phone at
          <Link className="underline" href="tel:+919633211248">
            {" "}
            +91 96332 11248
          </Link>
          .
        </p>
      </section>
    </main>
  );
}
